# Generated by Django 4.2.4 on 2023-09-06 10:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kafedra nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Kafedra nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Kafedra nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Kafedra nomi')),
                ('sub_name', models.CharField(max_length=150, verbose_name='Sub nomi')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Kadedra haqida')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Kadedra haqida')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Kadedra haqida')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Kadedra haqida')),
            ],
        ),
        migrations.CreateModel(
            name='ChairsShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.chair')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('sub_name', models.CharField(max_length=255, verbose_name='Sub name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH.')),
                ('image', models.ImageField(default='./kafedra/avatar.jpg', upload_to='./kafedra/', verbose_name='Rasm')),
                ('position', models.TextField(blank=True, null=True, verbose_name='Ustoz haqida')),
                ('position_uz', models.TextField(blank=True, null=True, verbose_name='Ustoz haqida')),
                ('position_en', models.TextField(blank=True, null=True, verbose_name='Ustoz haqida')),
                ('position_ru', models.TextField(blank=True, null=True, verbose_name='Ustoz haqida')),
                ('academic_title', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Unvoni')),
                ('academic_title_uz', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Unvoni')),
                ('academic_title_en', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Unvoni')),
                ('academic_title_ru', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Unvoni')),
                ('is_head', models.BooleanField(default=False, verbose_name='Kafedra mudirimi?')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon nomer')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.chair', verbose_name='Kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Fakultet nomi')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='Fakultet nomi')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Fakultet nomi')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Fakultet nomi')),
                ('sub_name', models.CharField(max_length=250, verbose_name='fakultet_nomi')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Fakultet haqida')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Fakultet haqida')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Fakultet haqida')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Fakultet haqida')),
                ('chairs', models.ManyToManyField(through='faculty.ChairsShip', to='faculty.chair', verbose_name='Fafedralar')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('image', models.ImageField(default='./fakultet/avatar.jpg', upload_to='./fakultet/', verbose_name='Rasm')),
                ('academic_title', models.TextField(verbose_name='Unvoni')),
                ('academic_title_uz', models.TextField(null=True, verbose_name='Unvoni')),
                ('academic_title_en', models.TextField(null=True, verbose_name='Unvoni')),
                ('academic_title_ru', models.TextField(null=True, verbose_name='Unvoni')),
                ('is_dean', models.BooleanField(default=False, verbose_name='Dekanmi?')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon nomer')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.position')),
            ],
        ),
        migrations.AddField(
            model_name='chairsship',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
    ]
